"""Add RBAC tables: departments, modules, resources, actions, permissions, roles, user_roles, user_permissions, department_users, audit_logs, role_data_scopes, role_field_permissions

Revision ID: 0ccd9c691231
Revises: d7c9a2daa76b
Create Date: 2026-08-25 17:15:57.145367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0ccd9c691231'
down_revision: Union[str, None] = 'd7c9a2daa76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _safe_drop_constraint(table_name: str, column_name: str | None = None, constraint_name: str | None = None) -> None:
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        c_name = constraint_name or (f"{table_name}_{column_name}_fkey" if column_name else None)
        if c_name:
            op.execute(f'ALTER TABLE "{table_name}" DROP CONSTRAINT IF EXISTS "{c_name}"')
    else:
        try:
            if constraint_name:
                op.drop_constraint(constraint_name, table_name, type_='foreignkey')
        except Exception:
            pass


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='permission_status_module'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_modules_code'), 'modules', ['code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'PASSWORD_CHANGE', 'PASSWORD_RESET', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_ACTIVATED', 'USER_DEACTIVATED', 'USER_LOCKED', 'USER_UNLOCKED', 'ROLE_ASSIGNED', 'ROLE_REMOVED', 'ROLE_CREATED', 'ROLE_UPDATED', 'ROLE_DELETED', 'ROLE_DUPLICATED', 'PERMISSION_CHANGED', 'PERMISSION_GRANTED', 'PERMISSION_REVOKED', 'DEPARTMENT_CREATED', 'DEPARTMENT_UPDATED', 'DEPARTMENT_DELETED', 'DEPARTMENT_ASSIGNED', 'DEPARTMENT_REMOVED', 'MODULE_CREATED', 'MODULE_UPDATED', 'MODULE_DELETED', 'RESOURCE_CREATED', 'RESOURCE_UPDATED', 'RESOURCE_DELETED', 'ACTION_CREATED', 'ACTION_UPDATED', 'ACTION_DELETED', name='audit_action_type'), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='permission_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['head_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='permission_status_resource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'code', name='uq_module_resource_code')
    )
    op.create_index(op.f('ix_resources_code'), 'resources', ['code'], unique=False)
    op.create_index(op.f('ix_resources_module_id'), 'resources', ['module_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='permission_status_role'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='permission_status_action'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'code', name='uq_resource_action_code')
    )
    op.create_index(op.f('ix_actions_code'), 'actions', ['code'], unique=False)
    op.create_index(op.f('ix_actions_resource_id'), 'actions', ['resource_id'], unique=False)
    op.create_table('department_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department_id', name='uq_user_department')
    )
    op.create_index(op.f('ix_department_users_department_id'), 'department_users', ['department_id'], unique=False)
    op.create_index(op.f('ix_department_users_user_id'), 'department_users', ['user_id'], unique=False)
    op.create_table('role_field_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('permission_type', sa.Enum('VISIBLE', 'HIDDEN', 'READ_ONLY', 'EDITABLE', 'REQUIRED', name='field_permission_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module_id', 'resource_id', 'field_name', name='uq_role_field_permission')
    )
    op.create_index(op.f('ix_role_field_permissions_module_id'), 'role_field_permissions', ['module_id'], unique=False)
    op.create_index(op.f('ix_role_field_permissions_resource_id'), 'role_field_permissions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_role_field_permissions_role_id'), 'role_field_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='permission_status_perm'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'resource_id', 'action_id', name='uq_module_resource_action')
    )
    op.create_index(op.f('ix_permissions_action_id'), 'permissions', ['action_id'], unique=False)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_module_id'), 'permissions', ['module_id'], unique=False)
    op.create_index(op.f('ix_permissions_resource_id'), 'permissions', ['resource_id'], unique=False)
    op.create_table('role_data_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.Enum('ALL', 'DEPARTMENT', 'TEAM', 'OWN', 'ASSIGNED', 'CUSTOM', name='data_scope_type'), nullable=False),
    sa.Column('custom_department_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module_id', 'resource_id', 'action_id', name='uq_role_data_scope')
    )
    op.create_index(op.f('ix_role_data_scopes_action_id'), 'role_data_scopes', ['action_id'], unique=False)
    op.create_index(op.f('ix_role_data_scopes_module_id'), 'role_data_scopes', ['module_id'], unique=False)
    op.create_index(op.f('ix_role_data_scopes_resource_id'), 'role_data_scopes', ['resource_id'], unique=False)
    op.create_index(op.f('ix_role_data_scopes_role_id'), 'role_data_scopes', ['role_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uq_user_permission')
    )
    op.create_index(op.f('ix_user_permissions_permission_id'), 'user_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    _safe_drop_constraint('activities', constraint_name='activities_application_id_fkey')
    op.create_foreign_key(None, 'activities', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'crm_lead_custom_field_values', 'users', ['verified_by_id'], ['id'], ondelete='SET NULL')
    _safe_drop_constraint('deliveries', constraint_name='deliveries_application_id_fkey')
    op.create_foreign_key(None, 'deliveries', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    _safe_drop_constraint('disbursements', constraint_name='disbursements_application_id_fkey')
    op.create_foreign_key(None, 'disbursements', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    _safe_drop_constraint('documents', constraint_name='documents_application_id_fkey')
    op.create_foreign_key(None, 'documents', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    _safe_drop_constraint('finance_submissions', constraint_name='finance_submissions_application_id_fkey')
    op.create_foreign_key(None, 'finance_submissions', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    _safe_drop_constraint('sanctions', constraint_name='sanctions_application_id_fkey')
    op.create_foreign_key(None, 'sanctions', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', name='user_status'), nullable=False))
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('profile_photo', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('reporting_manager_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['reporting_manager_id'], ['id'], ondelete='SET NULL')
    _safe_drop_constraint('verifications', constraint_name='verifications_application_id_fkey')
    op.create_foreign_key(None, 'verifications', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _safe_drop_constraint('verifications', constraint_name='verifications_application_id_fkey')
    op.create_foreign_key(None, 'verifications', 'applications', ['application_id'], ['id'])
    _safe_drop_constraint('users', constraint_name='users_reporting_manager_id_fkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'reporting_manager_id')
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'force_password_change')
    op.drop_column('users', 'status')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'username')
    _safe_drop_constraint('sanctions', constraint_name='sanctions_application_id_fkey')
    op.create_foreign_key(None, 'sanctions', 'applications', ['application_id'], ['id'])
    _safe_drop_constraint('finance_submissions', constraint_name='finance_submissions_application_id_fkey')
    op.create_foreign_key(None, 'finance_submissions', 'applications', ['application_id'], ['id'])
    _safe_drop_constraint('documents', constraint_name='documents_application_id_fkey')
    op.create_foreign_key(None, 'documents', 'applications', ['application_id'], ['id'])
    _safe_drop_constraint('disbursements', constraint_name='disbursements_application_id_fkey')
    op.create_foreign_key(None, 'disbursements', 'applications', ['application_id'], ['id'])
    _safe_drop_constraint('deliveries', constraint_name='deliveries_application_id_fkey')
    op.create_foreign_key(None, 'deliveries', 'applications', ['application_id'], ['id'])
    _safe_drop_constraint('crm_lead_custom_field_values', constraint_name='crm_lead_custom_field_values_verified_by_id_fkey')
    _safe_drop_constraint('activities', constraint_name='activities_application_id_fkey')
    op.create_foreign_key(None, 'activities', 'applications', ['application_id'], ['id'])
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_permission_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_role_data_scopes_role_id'), table_name='role_data_scopes')
    op.drop_index(op.f('ix_role_data_scopes_resource_id'), table_name='role_data_scopes')
    op.drop_index(op.f('ix_role_data_scopes_module_id'), table_name='role_data_scopes')
    op.drop_index(op.f('ix_role_data_scopes_action_id'), table_name='role_data_scopes')
    op.drop_table('role_data_scopes')
    op.drop_index(op.f('ix_permissions_resource_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_module_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_field_permissions_role_id'), table_name='role_field_permissions')
    op.drop_index(op.f('ix_role_field_permissions_resource_id'), table_name='role_field_permissions')
    op.drop_index(op.f('ix_role_field_permissions_module_id'), table_name='role_field_permissions')
    op.drop_table('role_field_permissions')
    op.drop_index(op.f('ix_department_users_user_id'), table_name='department_users')
    op.drop_index(op.f('ix_department_users_department_id'), table_name='department_users')
    op.drop_table('department_users')
    op.drop_index(op.f('ix_actions_resource_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_code'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resources_module_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_code'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_modules_code'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
