"""kim_pm_v1

Revision ID: ca3c7dcdc037
Revises: 20260904_tasks_clickup
Create Date: 2026-09-09 16:17:46.901424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca3c7dcdc037'
down_revision: Union[str, None] = '20260904_tasks_clickup'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_off_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week')
    )
    op.create_table('working_calendar_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('recurs_yearly', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_source', sa.Enum('WEBSITE', 'REFERRAL', 'EVENT', 'SOCIAL_MEDIA', 'COLD_CALL', 'OTHER', name='lead_source'), nullable=True))
        batch_op.add_column(sa.Column('lead_score', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_applications_lead_source'), ['lead_source'], unique=False)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_branches_code'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_branches_code'))
        batch_op.create_index(batch_op.f('ix_branches_code'), ['code'], unique=True)

    with op.batch_alter_table('cost_centers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_cost_centers_code'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_cost_centers_code'))
        batch_op.create_index(batch_op.f('ix_cost_centers_code'), ['code'], unique=True)

    with op.batch_alter_table('crm_lead_custom_field_values', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['verified_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('disbursements', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('finance_submissions', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hr_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_attendance_date'))
        batch_op.create_index(batch_op.f('ix_hr_attendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_unique_constraint('uq_user_attendance_date', ['user_id', 'attendance_date'])

    with op.batch_alter_table('hr_payroll', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_payroll_month', ['user_id', 'payroll_month'])

    with op.batch_alter_table('hr_performance_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_performance_reviews_reviewer_id'))

    with op.batch_alter_table('project_milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rollup_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rollup_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rollup_estimated_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('rollup_actual_cost', sa.Float(), nullable=False))
        batch_op.drop_column('is_completed')
        batch_op.drop_column('due_date')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('rollup_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rollup_end_date', sa.Date(), nullable=True))
        batch_op.create_unique_constraint(None, ['prefix'])

    with op.batch_alter_table('sanctions', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predecessor_task_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lag_days', sa.Integer(), nullable=False))
        batch_op.alter_column('dependency_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('FS', 'SS', 'FF', 'SF', name='task_dependency_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'BLOCKS'"))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_depends_on_task_id'))
        batch_op.drop_constraint(batch_op.f('uq_task_dependency'), type_='unique')
        batch_op.create_unique_constraint('uq_task_dependency', ['task_id', 'predecessor_task_id'])
        batch_op.create_index(batch_op.f('ix_task_dependencies_predecessor_task_id'), ['predecessor_task_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_tdep_depends_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['predecessor_task_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('depends_on_task_id')

    with op.batch_alter_table('task_relationships', schema=None) as batch_op:
        batch_op.alter_column('relationship_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('RELATED', 'LINKED', 'DUPLICATE', name='task_relationship_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'RELATED'"))

    with op.batch_alter_table('task_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed_type', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('exclude_from_active_totals', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_default_on_create', sa.Boolean(), nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('NOT_STARTED', 'ACTIVE', 'DONE', 'CLOSED', name='task_status_category'),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))

    with op.batch_alter_table('task_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_tags_name'))
        batch_op.create_index(batch_op.f('ix_task_tags_name'), ['name'], unique=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('actual_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('duration_working_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('task_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('URGENT', 'HIGH', 'NORMAL', 'LOW', name='task_priority'),
               existing_nullable=False,
               existing_server_default=sa.text("'NORMAL'"))
        batch_op.create_index(batch_op.f('ix_tasks_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_foreign_key(None, 'project_milestones', ['milestone_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['reporting_manager_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('verifications', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        pass

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        pass
        batch_op.drop_index(batch_op.f('ix_tasks_milestone_id'))
        batch_op.alter_column('priority',
               existing_type=sa.Enum('URGENT', 'HIGH', 'NORMAL', 'LOW', name='task_priority'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'NORMAL'"))
        batch_op.alter_column('task_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('sort_order')
        batch_op.drop_column('duration_working_days')
        batch_op.drop_column('actual_cost')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('completion_date')
        batch_op.drop_column('milestone_id')

    with op.batch_alter_table('task_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_tags_name'))
        batch_op.create_index(batch_op.f('ix_task_tags_name'), ['name'], unique=False)

    with op.batch_alter_table('task_statuses', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('NOT_STARTED', 'ACTIVE', 'DONE', 'CLOSED', name='task_status_category'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
        batch_op.drop_column('is_default_on_create')
        batch_op.drop_column('exclude_from_active_totals')
        batch_op.drop_column('is_completed_type')

    with op.batch_alter_table('task_relationships', schema=None) as batch_op:
        batch_op.alter_column('relationship_type',
               existing_type=sa.Enum('RELATED', 'LINKED', 'DUPLICATE', name='task_relationship_type'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'RELATED'"))

    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depends_on_task_id', sa.INTEGER(), nullable=False))
        pass
        batch_op.create_foreign_key(batch_op.f('fk_tdep_depends_id'), 'tasks', ['depends_on_task_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_task_dependencies_predecessor_task_id'))
        batch_op.drop_constraint('uq_task_dependency', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_task_dependency'), ['task_id', 'depends_on_task_id'])
        batch_op.create_index(batch_op.f('ix_task_dependencies_depends_on_task_id'), ['depends_on_task_id'], unique=False)
        batch_op.alter_column('dependency_type',
               existing_type=sa.Enum('FS', 'SS', 'FF', 'SF', name='task_dependency_type'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'BLOCKS'"))
        batch_op.drop_column('lag_days')
        batch_op.drop_column('predecessor_task_id')

    with op.batch_alter_table('sanctions', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        pass
        batch_op.drop_column('rollup_end_date')
        batch_op.drop_column('rollup_start_date')
        batch_op.drop_column('prefix')

    with op.batch_alter_table('project_milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=False))
        batch_op.drop_column('rollup_actual_cost')
        batch_op.drop_column('rollup_estimated_cost')
        batch_op.drop_column('rollup_end_date')
        batch_op.drop_column('rollup_start_date')

    with op.batch_alter_table('hr_performance_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_performance_reviews_reviewer_id'), ['reviewer_id'], unique=False)

    with op.batch_alter_table('hr_payroll', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_payroll_month', type_='unique')

    with op.batch_alter_table('hr_attendance', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_attendance_date', type_='unique')
        batch_op.drop_index(batch_op.f('ix_hr_attendance_attendance_date'))
        batch_op.create_index(batch_op.f('ix_hr_attendance_date'), ['attendance_date'], unique=False)

    with op.batch_alter_table('finance_submissions', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('disbursements', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('crm_lead_custom_field_values', schema=None) as batch_op:
        pass

    with op.batch_alter_table('cost_centers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_centers_code'))
        batch_op.create_index(batch_op.f('ix_cost_centers_code'), ['code'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_cost_centers_code'), ['code'])

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_code'))
        batch_op.create_index(batch_op.f('ix_branches_code'), ['code'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_branches_code'), ['code'])

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_lead_source'))
        batch_op.drop_column('lead_score')
        batch_op.drop_column('lead_source')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    op.drop_table('working_calendar_holidays')
    op.drop_table('weekly_off_days')
    # ### end Alembic commands ###
